---
- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: false
  handlers:
    - name: Start clickhouse service
#      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: '644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: '644'
    - name: Install clickhouse packages
#      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0


- name: Install Vector
  hosts: clickhouse
  gather_facts: false
  tasks:
    - name: Create directory for distr
      ansible.builtin.file:
        path: /vectordistr
        state: directory
        mode: '755'
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.1/vector-0.21.1-x86_64-unknown-linux-musl.tar.gz"
        dest: "/vectordistr/vector-0.21.1-x86_64-unknown-linux-musl.tar.gz"
        mode: '644'
    - name: Create directory for install vector
      ansible.builtin.file:
        path: /vector
        state: directory
        mode: '755'
    - name: Unpack vector
      ansible.builtin.unarchive:
        src: "/vectordistr/vector-0.21.1-x86_64-unknown-linux-musl.tar.gz"
        dest: "/vector"
        remote_src: true
        extra_opts: [--strip-components=2]
    - name: Start vector
      ansible.builtin.shell: "nohup /vector/bin/vector --config /vector/config/vector.toml </dev/null >/dev/null 2>&1 &"
      register: rescmd
      changed_when: rescmd.rc == 0
