---
- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: true
  roles:
    - { role: clickhouse }

- name: Install Vector 
  hosts: vector
  gather_facts: true
  become: true
  roles:
    - { role: vector-role }

- name: Download lighthouse
  hosts: lighthouse
  gather_facts: true
  become: true
  roles:
    - { role: lighthouse-role }

- name: Install nginx
  hosts: lighthouse
  become: true
  tasks:
    - name: install epel
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: copy nginx cfg
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
    - name: start-nginx
      ansible.builtin.command: nginx
